### ISSUE TITLE
ImportError thrown with version nyc-crime-map==0.3.1

### ISSUE THREAD

**Issue by lelap** [tlevine/nyc-crime-map#2]
ImportError: cannot import name 'html' is thrown when using the 0.3.1 version. This issue does not exist in 0.1

**Comment by tlevine** [comment]
Thanks for reporting this.

I do not see "html" anywhere in the present source code nor the 0.1
source code,

    $ git checkout v0.1
    $ grep -r html .
    $ git checkout v0.3.1
    $ grep -r html .

so this error is very interesting! Could you send the entire error
message?

**Comment by lelap** [comment]
Sure - this is the full error below. I'm testing this on a Mac and
also on Umbunu 14.04. I'm installing nyc-crime-map through PyPI.
Version .1 is working for me on both platforms.

Traceback (most recent call last):
  File "/Users/lela/dnainfo/doitt/otherenv/bin/nyc-crime-map", line 9,
in <module>
    load_entry_point('nyc-crime-map==0.3.2', 'console_scripts',
'nyc-crime-map')()
  File "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/pkg_resources.py",
line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/pkg_resources.py",
line 2431, in load_entry_point
    return ep.load()
  File "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/pkg_resources.py",
line 2147, in load
    ['__name__'])
  File "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/nyc_crime_map/__init__.py",
line 3, in <module>
    from .download import table_features_first, table_features_tail
  File "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/nyc_crime_map/download.py",
line 4, in <module>
    import vlermv, requests
  File "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/vlermv/__init__.py",
line 1, in <module>
    from ._vlermv import Vlermv
  File "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/vlermv/_vlermv.py",
line 10, in <module>
    from .serializers import pickle
  File "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/vlermv/serializers/__init__.py",
line 2, in <module>
    from ._lxml import html, xml
ImportError: cannot import name 'html'

On Wed, May 13, 2015 at 3:40 AM, Thomas Levine <notifications@github.com> wrote:
> Thanks for reporting this.
>
> I do not see "html" anywhere in the present source code nor the 0.1
> source code,
>
> $ git checkout v0.1
> $ grep -r html .
> $ git checkout v0.3.1
> $ grep -r html .
>
> so this error is very interesting! Could you send the entire error
> message?
>
> On 12 May 18:38, Lela wrote:
>> ImportError: cannot import name 'html' is thrown when using the 0.3.1
>> version. This issue does not exist in 0.1
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/tlevine/nyc-crime-map/issues/2
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Lela Prashad, Chief Data Scientist
NiJeL - Data. Mapping. Community Impact.
mobile: 602.412.1553
email: lprashad@nijel.org
Brooklyn, NYC, USA

**Comment by tlevine** [comment]
Thanks. I have uploaded a new version that should fix your issue.
If you're using pip or easy_install, something like this should
install the new version.

    pip install nyc-crime-map --upgrade

In case you're installing the packages manually, you probably
just need to upgrade vlermv (http://pypi.python.org/pypi/vlermv).

The the issue was that it loaded a library that tried to load a
library that you don't have installed. This tertiary library shouldn't
be necessary, and that's what I fixed, in the secondary library.

Tom

**Comment by lelap** [comment]
Thanks, Tom!

Lela

On Wed, May 13, 2015 at 5:55 PM, Thomas Levine <notifications@github.com>
wrote:

> Thanks. I have uploaded a new version that should fix your issue.
> If you're using pip or easy_install, something like this should
> install the new version.
>
> pip install nyc-crime-map --upgrade
>
> In case you're installing the packages manually, you probably
> just need to upgrade vlermv (http://pypi.python.org/pypi/vlermv).
>
> The the issue was that it loaded a library that tried to load a
> library that you don't have installed. This tertiary library shouldn't
> be necessary, and that's what I fixed, in the secondary library.
>
> Tom
>
>
> On 13 May 13:41, Lela wrote:
> > Sure - this is the full error below. I'm testing this on a Mac and
> > also on Umbunu 14.04. I'm installing nyc-crime-map through PyPI.
> > Version .1 is working for me on both platforms.
> >
> > Traceback (most recent call last):
> > File "/Users/lela/dnainfo/doitt/otherenv/bin/nyc-crime-map", line 9,
> > in <module>
> > load_entry_point('nyc-crime-map==0.3.2', 'console_scripts',
> > 'nyc-crime-map')()
> > File
> "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/pkg_resources.py",
> > line 356, in load_entry_point
> > return get_distribution(dist).load_entry_point(group, name)
> > File
> "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/pkg_resources.py",
> > line 2431, in load_entry_point
> > return ep.load()
> > File
> "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/pkg_resources.py",
> > line 2147, in load
> > ['__name__'])
> > File
> "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/nyc_crime_map/__init__.py",
> > line 3, in <module>
> > from .download import table_features_first, table_features_tail
> > File
> "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/nyc_crime_map/download.py",
> > line 4, in <module>
> > import vlermv, requests
> > File
> "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/vlermv/__init__.py",
> > line 1, in <module>
> > from ._vlermv import Vlermv
> > File
> "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/vlermv/_vlermv.py",
> > line 10, in <module>
> > from .serializers import pickle
> > File
> "/Users/lela/dnainfo/doitt/otherenv/lib/python3.4/site-packages/vlermv/serializers/__init__.py",
> > line 2, in <module>
> > from ._lxml import html, xml
> > ImportError: cannot import name 'html'
> >
> > On Wed, May 13, 2015 at 3:40 AM, Thomas Levine <notifications@github.com>
> wrote:
> > > Thanks for reporting this.
> > >
> > > I do not see "html" anywhere in the present source code nor the 0.1
> > > source code,
> > >
> > > $ git checkout v0.1
> > > $ grep -r html .
> > > $ git checkout v0.3.1
> > > $ grep -r html .
> > >
> > > so this error is very interesting! Could you send the entire error
> > > message?
> > >
> > > On 12 May 18:38, Lela wrote:
> > >> ImportError: cannot import name 'html' is thrown when using the 0.3.1
> > >> version. This issue does not exist in 0.1
> > >>
> > >> ---
> > >> Reply to this email directly or view it on GitHub:
> > >> https://github.com/tlevine/nyc-crime-map/issues/2
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> >
> >
> >
> > --
> > Lela Prashad, Chief Data Scientist
> > NiJeL - Data. Mapping. Community Impact.
> > mobile: 602.412.1553
> > email: lprashad@nijel.org
> > Brooklyn, NYC, USA
> >
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/tlevine/nyc-crime-map/issues/2#issuecomment-101808200
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tlevine/nyc-crime-map/issues/2#issuecomment-101827506>
> .
>



-- 
Lela Prashad, Chief Data Scientist
NiJeL - Data. Mapping. Community Impact.
mobile: 602.412.1553
email: lprashad@nijel.org
Brooklyn, NYC, USA
